name: CI - Build and Push Lambda Images

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Lambda images
        run: |
          IMAGE_TAG=${{ github.sha }}
          for FUNC in scanner action ai_insights; do
            docker build -t $FUNC-lambda ./lambdas/$FUNC
            docker tag $FUNC-lambda:latest 982081047984.dkr.ecr.us-east-1.amazonaws.com/$FUNC-lambda:$IMAGE_TAG
            docker push 982081047984.dkr.ecr.us-east-1.amazonaws.com/$FUNC-lambda:$IMAGE_TAG
          done
